defmodule Jagua.Repo.Migrations.InitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:sentinels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :token, :text, null: false
      add :interval, :text, null: false
      add :status, :text, default: "pending"
      add :alert_type, :text, default: "basic"
      add :notes, :text
      add :tags, {:array, :text}, default: []
      add :paused_at, :utc_datetime_usec
      add :last_check_in_at, :utc_datetime_usec
      add :next_alert_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid, null: false
    end

    create table(:sentinel_check_ins, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :message, :text
      add :exit_code, :bigint, default: 0
      add :status, :text, default: "ok"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sentinel_id,
          references(:sentinels,
            column: :id,
            name: "sentinel_check_ins_sentinel_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:sentinels) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "sentinels_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:sentinels, [:token], name: "sentinels_unique_token_index")

    alter table(:projects) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :public_status_page, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "projects_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    create table(:project_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_memberships_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "project_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:project_memberships, [:project_id, :user_id],
             name: "project_memberships_unique_membership_index"
           )

    create table(:passkey_credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :credential_id, :binary, null: false
      add :public_key, :binary, null: false
      add :sign_count, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "passkey_credentials_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:passkey_credentials, [:credential_id],
             name: "passkey_credentials_unique_credential_index"
           )

    create table(:magic_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token_hash, :text, null: false
      add :used_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "magic_links_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :prefix, :text, null: false
      add :key_hash, :text, null: false
      add :last_used_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "api_keys_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:alert_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :payload, :map, default: %{}
      add :sent_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :sentinel_id,
          references(:sentinels,
            column: :id,
            name: "alert_events_sentinel_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :alert_channel_id, :uuid, null: false
    end

    create table(:alert_channels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:alert_events) do
      modify :alert_channel_id,
             references(:alert_channels,
               column: :id,
               name: "alert_events_alert_channel_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:alert_channels) do
      add :name, :text, null: false
      add :type, :text, null: false
      add :config, :map, default: %{}
      add :enabled, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "alert_channels_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:alert_channels, "alert_channels_project_id_fkey")

    alter table(:alert_channels) do
      remove :project_id
      remove :updated_at
      remove :inserted_at
      remove :enabled
      remove :config
      remove :type
      remove :name
    end

    drop constraint(:alert_events, "alert_events_alert_channel_id_fkey")

    alter table(:alert_events) do
      modify :alert_channel_id, :uuid
    end

    drop table(:alert_channels)

    drop constraint(:alert_events, "alert_events_sentinel_id_fkey")

    drop table(:alert_events)

    drop constraint(:api_keys, "api_keys_project_id_fkey")

    drop table(:api_keys)

    drop constraint(:magic_links, "magic_links_user_id_fkey")

    drop table(:magic_links)

    drop_if_exists unique_index(:passkey_credentials, [:credential_id],
                     name: "passkey_credentials_unique_credential_index"
                   )

    drop constraint(:passkey_credentials, "passkey_credentials_user_id_fkey")

    drop table(:passkey_credentials)

    drop_if_exists unique_index(:project_memberships, [:project_id, :user_id],
                     name: "project_memberships_unique_membership_index"
                   )

    drop constraint(:project_memberships, "project_memberships_project_id_fkey")

    drop constraint(:project_memberships, "project_memberships_user_id_fkey")

    drop table(:project_memberships)

    drop_if_exists unique_index(:projects, [:slug], name: "projects_unique_slug_index")

    drop constraint(:projects, "projects_owner_id_fkey")

    alter table(:projects) do
      remove :owner_id
      remove :updated_at
      remove :inserted_at
      remove :public_status_page
      remove :slug
      remove :name
    end

    drop_if_exists unique_index(:sentinels, [:token], name: "sentinels_unique_token_index")

    drop constraint(:sentinels, "sentinels_project_id_fkey")

    alter table(:sentinels) do
      modify :project_id, :uuid
    end

    drop table(:projects)

    drop constraint(:sentinel_check_ins, "sentinel_check_ins_sentinel_id_fkey")

    drop table(:sentinel_check_ins)

    drop table(:sentinels)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)
  end
end
